/** The backend's port for the run; the playwright config derives its base URL from it. */
export const BENCH_PORT = Number(process.env.IRIS_E2E_PORT ?? 18_731);

// The bench's clips (generated by fixtures/make.sh), by the name the specs use.
export const CATALOG = {
	h264Mp4: { file: 'Bench.Alpha.2001.360p.WEB.H264.AAC-IRIS.mp4', duration: 60 },
	h264Mkv: { file: 'Bench.Bravo.2002.360p.WEB.H264.AAC-IRIS.mkv', duration: 90 },
	hevcEac3: { file: 'Bench.Charlie.2003.720p.WEB.HEVC.EAC3-IRIS.mkv', duration: 60 },
	hevcAac: { file: 'Bench.Kilo.2011.720p.WEB.HEVC.AAC-IRIS.mkv', duration: 60 },
	mono: { file: 'Bench.Delta.2004.360p.WEB.H264.AAC.Mono-IRIS.mp4', duration: 45 },
	surround: { file: 'Bench.Echo.2005.360p.WEB.H264.AAC5.1-IRIS.mp4', duration: 45 },
	noAudio: { file: 'Bench.Foxtrot.2006.360p.WEB.H264.NoAudio-IRIS.mp4', duration: 40 },
	ass: { file: 'Bench.Golf.2007.360p.WEB.H264.AAC.ASS-IRIS.mkv', duration: 60 },
	pgs: { file: 'Bench.Hotel.2008.360p.WEB.H264.AAC.PGS-IRIS.mkv', duration: 60 },
	h264Eac3: { file: 'Bench.India.2009.360p.WEB.H264.EAC3-IRIS.mkv', duration: 60 },
	heavy: { file: 'Bench.Juliet.2010.720p.WEB.H264.AAC-IRIS.mp4', duration: 120 },
	sync: { file: 'Bench.Lima.2012.360p.WEB.H264.AAC.Sync-IRIS.mp4', duration: 60 },
	syncLong: { file: 'Bench.Mike.2013.360p.WEB.H264.AAC.Sync-IRIS.mp4', duration: 1800 },
	ep1: { file: 'Bench.Show.S01E01.360p.WEB.H264.AAC-IRIS.mp4', duration: 30 },
	ep2: { file: 'Bench.Show.S01E02.360p.WEB.H264.AAC-IRIS.mp4', duration: 30 }
} as const;

export type ClipKey = keyof typeof CATALOG;

export interface BenchState {
	baseUrl: string;
	email: string;
	password: string;
	infohash: Record<ClipKey, string>;
	/** The live channel's path (`/live/fr/<id>`), null when the live source did not come up. */
	livePath: string | null;
	/** The Iris libav.js variant (AC-3 / E-AC-3) is in the build: the E-AC-3 cases can run. */
	libavIris: boolean;
	dataDir: string;
}
