[package]
name = "iris-torrent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
iris-core = { workspace = true }
iris-db = { workspace = true }
iris-media = { workspace = true }
utoipa = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
bytes = { workspace = true }
hex = { workspace = true }
anyhow = { workspace = true }
sqlx = { workspace = true }
librqbit = { workspace = true }
